### ISSUE TITLE
Show last reported vehicle position

### ISSUE THREAD

**Issue by bdougsand** [robsideshow/mbta-bustracker#55]
It would get noisy to show the LRP of every visible vehicle, but there should be some way of finding out both the age (see #54) and the position of the last vehicle report. Perhaps when a vehicle is selected? Or hovered?

**Comment by robsideshow** [comment]
Yes, absolutely agree that showing LRP for all vehicles would be confusing.  I would be in favor of only offering LRP age and position when a vehicle is selected.  Not sure how intuitive this is, since I think people might not know/suspect/realise that true positions are are only updated once per minute or maybe even less often than that.
