### ISSUE TITLE
If a vehicle and a stop are selected, highlight the vehicle's ETA in the stop popup if it's visible

### ISSUE THREAD

**Issue by bdougsand** [robsideshow/mbta-bustracker#83]
A couple questions:
- If a vehicle is traveling in one direction and the stop is currently showing buses/subways going in the other direction, should selecting the vehicle switch the stop's direction filter?
- Alternatively, should there be an exception, so that the selected vehicle prediction shows up in the stop popup even if it's traveling in the "wrong" direction? (Assuming that it's going through that stop at all.)

**Comment by robsideshow** [comment]
My inclination would be:
No, don't force-switch the direction of the stop ETA popup.
No, don't show it as an exception either.

I feel like this is a (very?) rare case for buses, since most stops are one-way.  For trains, eh, maybe the direction indicator for the opposite direction could turn red, or somehow be highlighted?

I don't feel very strongly about this issue, though.  Open to changing my mind.
